name: Build sQReen Reader

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Build with Maven
        run: ./mvnw clean verify

      - name: SonarCloud Scan
        run: ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Sonar Status
        run: |
          status=$(curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=matthew-js-porter_sqreen-reader)
          echo $status | jq '.'
          status=$(echo $status | jq '.projectStatus.status')
          test '"OK"' = $status
