name: Build sQReen Reader

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [ 'java' ]

    steps:
      - uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Build with Maven
        run: ./mvnw clean verify -Djava.awt.headless=true

      - name: SonarCloud Scan
        run: ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Djava.awt.headless=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Sonar Status
        run: |
          status=$(curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=matthew-js-porter_sqreen-reader)
          echo $status | jq '.'
          status=$(echo $status | jq '.projectStatus.status')
          test '"OK"' = $status

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          JAVA_HOME: /usr/java/openjdk-15

      - name: Deploy to Github Packages
        run: ./mvnw deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Build with Maven
        run: ./mvnw "-Djava.awt.headless=true" clean install

      - name: Deploy Installers
        run: ./mvnw deploy -pl sqreen-reader-installer -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}