name: Build sQReen Reader

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

  publish-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [15.x]
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.MAC_CODESIGN_CERT }}
          p12-password: ${{ secrets.MAC_CODESIGN_SECRET }}
      - name: publish packages
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  publish-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [15.x]
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: publish packages
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: publish packages
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}